######################################################################
# Automatically generated by qmake (3.1) Sun Apr 23 15:35:05 2017
######################################################################
QT += widgets multimedia
TEMPLATE = app
TARGET = AudioPlayer
INCLUDEPATH += .

# Input
HEADERS += AudioPlayer.h
SOURCES += AudioPlayer.cpp main.cpp
RESOURCES += res.qrc
